### ISSUE TITLE
Can't use with ActiveRecord

### ISSUE THREAD

**Issue by dwbutler** [headius/jruby-pg#11]
I tried using this gem as a drop-in replacement for `pg` while attempting to get Discourse to run on JRuby.

Due to [this line](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L13), the ActiveRecord Postgresql adapter is unable to recognize this gem as satisfying its requirements. I always get:

```
Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile.
```

I was able to get things to work by forking the gem and editing the gemspec.

I'm not sure what the correct long-term approach is. Either ActiveRecord should be fixed (ideal?), or the `gem` method itself needs to be patched (ugly?).

**Comment by pmontrasio** [comment]
I run into this problem now, after having seen the announcement of JRuby 9000 and tried to run a Rails 4.2 application with it. I could fork the gem and apply the patch from @dwbutler but haven't been any progresses since December 2013?

**Comment by Ch4s3** [comment]
:+1:
