### ISSUE TITLE
Incompatibilities with the pg gem

### ISSUE THREAD

**Issue by chanks** [headius/jruby-pg#12]
The following examples work as expected on the pg gem, but throw errors on jruby-pg 0.14.1.rc2-java:

    require 'pg'
    pg = PG::Connection.open :dbname => 'scrap'

    pg.async_exec("select now()", nil)
    PG::Error: org.jruby.RubyNil cannot be cast to org.jruby.RubyArray
        from org/jruby/pg/Connection.java:560:in `exec'
        from (irb):4:in `evaluate'
        from org/jruby/RubyKernel.java:1121:in `eval'
        from org/jruby/RubyKernel.java:1517:in `loop'
        from org/jruby/RubyKernel.java:1282:in `catch'
        from org/jruby/RubyKernel.java:1282:in `catch'
        from /home/chris/.rvm/rubies/jruby-1.7.5/bin/irb:13:in `(root)'

    pg.async_exec("select $1::boolean", [false])
    PG::Error: invalid input syntax for type boolean: "#<FalseClass:0x54fe71ff>"
        from org/jruby/pg/Connection.java:558:in `exec'
        from (irb):6:in `evaluate'
        from org/jruby/RubyKernel.java:1121:in `eval'
        from org/jruby/RubyKernel.java:1517:in `loop'
        from org/jruby/RubyKernel.java:1282:in `catch'
        from org/jruby/RubyKernel.java:1282:in `catch'
        from /home/chris/.rvm/rubies/jruby-1.7.5/bin/irb:13:in `(root)'

Thank you!

**Comment by jvshahid** [comment]
I verified this is still an issue with the current master. I think it should be easy to fix. I'll try to get this fixed before releasing the gem

**Comment by chanks** [comment]
Thanks! Really glad that this gem is getting some attention :smiley:

**Comment by jvshahid** [comment]
Sorry it took so long to get to these issues
