### ISSUE TITLE
Missing some exceptions

### ISSUE THREAD

**Issue by jgaskins** [headius/jruby-pg#15]
Trying to add JRuby support to [Perpetuity::Postgres](https://github.com/jgaskins/perpetuity-postgres). The good news is that almost 200 of the 214 specs pass. About 6 of the failures are due to a [JRuby bug](https://github.com/jruby/jruby/issues/1517) but the rest are due to missing exceptions:

- `PG::ConnectionBad`: I'm assuming this is a generic "we couldn't connect" exception, but I'm seeing it raised if the specified database doesn't exist.
- `PG::UndefinedFunction`: If you use a SQL function that isn't loaded or doesn't exist.
- `PG::UndefinedTable`: CRUD on a nonexistent table.
- `PG::UndefinedColumn`: Raised any time Postgres says `column "foo" does not exist`.

I think those are the only exceptions I'm missing in Perpetuity::Postgres. I'll update if I notice more.

**Comment by jvshahid** [comment]
This should be fixed on master. I think I got all the exceptions, at least the ones mentioned here. I'm planning to release this gem very soon. I'll post something on the jruby mailing list when the gem is released.
