### ISSUE TITLE
Java::JavaLang::NullPointerException when booting app

### ISSUE THREAD

**Issue by tmornini** [headius/jruby-pg#16]
Hello @headius! I'm working on the next version of Subledger and am trying to keep my runtime options open. The system is built around Reel web server and the Celluloid ecosystem and mindset.

I'm having a hard time getting it running on JRuby. I'm using the pg gem and found jruby-pg and it appeared to cover my needs as a pg replacement.

However, upon booting on JRuby, the app crashes with the following exception. It's worth noting that it doesn't crash when I send it a request, but simply upon booting.

I tried to re-create a minimum crash example, but came up short. When isolated from the rest of the system, my DbConnection cell behaved just fine on JRuby using jruby-pg.

Can you tell from the backtrace what might be happening?

    v3 $ ./api.rb 
    E, [2014-04-06T22:11:57.729000 #62114] ERROR -- : Subledger::Operations::Utilities::Aws::DbConnection crashed!
    Java::JavaLang::NullPointerException: 
      org.jruby.pg.PostgresHelpers.stringify(PostgresHelpers.java:9)
      org.jruby.pg.Connection.parse_args(Connection.java:352)
      org.jruby.pg.Connection.initialize(Connection.java:397)
      org.jruby.pg.Connection$INVOKER$i$0$0$initialize.call(Connection$INVOKER$i$0$0$initialize.gen)
      org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:665)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
      org.jruby.RubyClass.newInstance(RubyClass.java:804)
      org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
      org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrNBlock.call(JavaMethod.java:297)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
      org.jruby.ast.CallSpecialArgNode.interpret(CallSpecialArgNode.java:67)
      org.jruby.ast.ReturnNode.interpret(ReturnNode.java:92)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
      org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
      org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:198)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
      org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
      org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)
      org.jruby.ast.OpAsgnOrNode.interpret(OpAsgnOrNode.java:102)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
      org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
      org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:164)
      org.jruby.RubyClass.finvoke(RubyClass.java:548)
      org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1531)
      org.jruby.RubyBasicObject$INVOKER$i$send19.call(RubyBasicObject$INVOKER$i$send19.gen)
      org.jruby.RubyKernel.public_send(RubyKernel.java:1965)
      org.jruby.RubyKernel$INVOKER$s$0$0$public_send.call(RubyKernel$INVOKER$s$0$0$public_send.gen)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:356)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:213)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
      org.jruby.ast.CallSpecialArgBlockPassNode.interpret(CallSpecialArgBlockPassNode.java:66)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
      org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
      org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)
      org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:206)
      org.jruby.runtime.callsite.SuperCallSite.callBlock(SuperCallSite.java:190)
      org.jruby.runtime.callsite.SuperCallSite.call(SuperCallSite.java:197)
      org.jruby.runtime.callsite.SuperCallSite.callVarargs(SuperCallSite.java:108)
      org.jruby.ast.SuperNode.interpret(SuperNode.java:115)
      org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
      org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
      org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
      org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
      org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:198)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
      org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
      org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:130)
      org.jruby.runtime.Block.yieldSpecific(Block.java:111)
      org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.IfNode.interpret(IfNode.java:118)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
      org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:130)
      org.jruby.runtime.Block.yieldSpecific(Block.java:111)
      org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
      org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
      org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
      org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
      org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:130)
      org.jruby.runtime.Block.yieldSpecific(Block.java:111)
      org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:177)
      org.jruby.runtime.Block.yieldArray(Block.java:158)
      org.jruby.ext.fiber.ThreadFiber$1.run(ThreadFiber.java:222)
      java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
      java.lang.Thread.run(Thread.java:695)

**Comment by jvshahid** [comment]
The version on master uses environment variables if the value of the given parameter is missing from the connection info string/hash. I'm planing to release the gem soon, I'll post a message on the JRuby mailing list as soon as this is done.
