### ISSUE TITLE
Wrong info in README

### ISSUE THREAD

**Issue by andriytyurnikov** [headius/jruby-pg#22]
```
gem install jruby-pg
ERROR:  Could not find a valid gem 'jruby-pg' (>= 0) in any repository
```

**Comment by jvshahid** [comment]
README has been updated in f698254b608056096ef458a6014f532007198b60 and the new version is pushed to rubygems. **NOTE** the gem name should be `pg_jruby`, i decided to stick to that name because that's what we used for the first version of the gem.
