### ISSUE TITLE
How to use with Rails?

### ISSUE THREAD

**Issue by khelll** [headius/jruby-pg#23]
getting this:

Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

What is the adapter type I should have?

**Comment by Ch4s3** [comment]
:+1:

**Comment by jvshahid** [comment]
did you try to run `gem install pg_jruby` ?

**Comment by Ch4s3** [comment]
So I have the following in my gemfile:
````ruby
platform :jruby do
  gem 'pg_jruby', '0.17.1', :git => 'git://github.com/headius/jruby-pg.git', :branch => :master
  gem "jruby-openssl"
end
````

I run `bundle install`,  and when I run `rails console` I get:
````
Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
                                        spec at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/connection_specification.rb:190
                        establish_connection at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activerecord-4.1.12/lib/active_record/connection_handling.rb:50
                            block in Railtie at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activerecord-4.1.12/lib/active_record/railtie.rb:127
                               instance_eval at org/jruby/RubyBasicObject.java:1636
                                execute_hook at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38
                            block in on_load at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:28
                                        each at org/jruby/RubyArray.java:1560
                                     on_load at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27
                            block in Railtie at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activerecord-4.1.12/lib/active_record/railtie.rb:116
                               instance_exec at org/jruby/RubyBasicObject.java:1673
                                         run at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/initializable.rb:30
                   block in run_initializers at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/initializable.rb:55
                         block in tsort_each at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:226
  block in each_strongly_connected_component at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:348
      each_strongly_connected_component_from at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:429
  block in each_strongly_connected_component at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:347
                                        each at org/jruby/RubyArray.java:1560
                                        call at org/jruby/RubyMethod.java:127
           each_strongly_connected_component at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:345
                                  tsort_each at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:224
                                  tsort_each at /Users/chase/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:203
                            run_initializers at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/initializable.rb:54
                                 initialize! at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/application.rb:300
                                       <top> at /Users/chase/code/athene/config/environment.rb:5
                                     require at org/jruby/RubyKernel.java:940
                             block in (root) at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:1
                             load_dependency at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232
                                     require at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247
                                     require at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247
                        require_environment! at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/application.rb:276
        require_application_and_environment! at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:147
                                     console at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:68
                                       <top> at /Users/chase/.rvm/gems/jruby-9.0.0.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:40
                                     require at org/jruby/RubyKernel.java:940
                                       <top> at bin/rails:4
````

**Comment by Ch4s3** [comment]
What ever happened with this https://github.com/ged/ruby-pg/pull/1?

**Comment by jvshahid** [comment]
I added some instructions to the (readme)[https://github.com/headius/jruby-pg/#how-to-install] on how to use the gem with rails. please give it a try and let me know if it doesn't work for you

**Comment by jvshahid** [comment]
@Ch4s3 by the time i was in par with `0.17.1` the ruby-pg gem has moved to `0.18` which broke some tests for me. They added some new features that will have to be implemented in order to merge the pr. I don't have time to work on gem unfortunately but i'm happy to review prs if someone wants to give me a hand.

**Comment by Ch4s3** [comment]
That's exactly what I did. No worries, I can keep using the activerecord-jbdc-adapter .

**Comment by jvshahid** [comment]
@Ch4s3 there are some differences to what you did, the gem line in the Gemfile says `gem 'pg'` and the jar file is now part of the repo.

**Comment by Ch4s3** [comment]
Sorry, I'm not sure I understand what I need to do beyond adding `gem 'pg_jruby', '0.17.1', :git => 'git://github.com/headius/jruby-pg.git', :branch => :master` to my gemfile.

**Comment by jvshahid** [comment]
@Ch4s3 replace `gem 'pg_jruby`' with `gem 'pg'` and try again.

**Comment by Ch4s3** [comment]
Interesting, that works. However, it locks me in to using only jruby, and I can't drop back to MRI in development. Maybe I can take a look at your old PR on the main pg gem.

**Comment by jvshahid** [comment]
You can use bundler `:platforms => jruby` to enable the gem on jruby only. That said, I haven't tried it. Let me know if this work, I can update the README to provide more information for this use case.

**Comment by Ch4s3** [comment]
I have 
```ruby
platform :jruby do
  ...
end
```
and
```ruby
platform :ruby do
  ...
end
```

Bundler doesn't seem to like having `gem pg` defined in both places.

**Comment by marlonoso** [comment]
I'm getting the same error msg, but I'm using ActiveRecord outside Rails in a pure rb script

Gemfile

    source 'https://rubygems.org'
    gem 'activerecord'
    gem 'nokogiri'
    #gem 'pg', '~> 0.18.2'
    gem 'pg', '0.18', :platform => :jruby, :git => 'git://github.com/headius/jruby-pg.git', :branch => :master
    #gem 'activerecord-jdbc-adapter', platform: :jruby

`bundle install ` then `jruby worker.rb` then error

`Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add gem 'pg' to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
                  spec at /home/marlon/.rvm/gems/jruby-9.0.5.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/connection_specification.rb:177
  establish_connection at /home/marlon/.rvm/gems/jruby-9.0.5.0/gems/activerecord-4.2.5.1/lib/active_record/connection_handling.rb:50
                 <top> at /home/marlon/app/analyzer/models.rb:3
               require at org/jruby/RubyKernel.java:937
               require at /home/marlon/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:121
       <module:Worker> at worker.rb:3
                 <top> at worker.rb:1
`

/home/marlon/app/analyzer/models.rb:3

    ActiveRecord::Base.establish_connection(
      :adapter => 'postgresql',
      :host => 'mydatabase.amazonaws.com',
      :username => 'user',
      :password => 'pwd',
      :database => 'mydb',
      :schema_search_path => "myssp"
    )

**Comment by jvshahid** [comment]
I added a link to a sample app using jruby-pg.
