### ISSUE TITLE
What is the purpose of this project?

### ISSUE THREAD

**Issue by jjb** [headius/jruby-pg#27]
What is the purpose of this project? What's wrong with using the pg gem with jruby?

I'll make a PR to explain this in the readme.

Thanks!
John

**Comment by jvshahid** [comment]
The `pg` gem requires C extensions, which isn't fully supported in JRuby AFAIK. Few years ago, @headius asked for the help of the community to rewrite popular ruby gems in pure java and this is the result of rewriting the `pg` gem.

**Comment by jjb** [comment]
Thanks! That's exactly what I thought, but.... I currently don't have jruby-pg in my Gemfile or Gemfile.lock and afaik all the environments where I test and run my app don't support compiling C extensions, so how is it that I've been happily using the pg gem all these years?

**Comment by jjb** [comment]
http://lists.ruby-lang.org/pipermail/jruby/2015-November/000136.html

**Comment by jvshahid** [comment]
The gemfile you provided makes perfect sense. You are using jdbc when running in a JRuby VM. In case you are wondering what this project adds, `jruby-pg` provides few interfaces that the jdbc adapter doesn't have. Most use cases don't require those interfaces, specially if you are using activerecord, afaik. Extra apis in the pg & jruby-pg gem include:

- Async API for querying
- Large objects API
- Bulk `Copy` API
- Notification API

I hope this answers your question.

**Comment by jjb** [comment]
Thanks! I've added this explanation to the readme in #29
